### ISSUE TITLE
Bring in external changes.

### ISSUE THREAD

**Issue by niemyjski** [csnover/TraceKit#14]
Bring in external changes from raygun / raven and others who have made changes in their local repo.

**Comment by niemyjski** [comment]
https://github.com/getsentry/raven-js/issues/345

**Comment by niemyjski** [comment]
https://github.com/MindscapeHQ/raygun4js/issues/114

**Comment by niemyjski** [comment]
I've been trying to get a hold of raven to talk about some of their changes. I'll need to create some unit tests before I do any more merging.

**Comment by niemyjski** [comment]
We may want to see what improvements we can make via ( https://bugsnag.com/blog/js-stacktraces/ )

**Comment by niemyjski** [comment]
I just asked a bunch of detailed questions here: https://github.com/getsentry/raven-js/issues/345 I'd like to bring in some of their changes but I have questions.

**Comment by dcramer** [comment]
Some changes that would need pulled in from raven.js before we'd consider using upstream:

- lastArgs in processLastException
- rethrow argument on report

Other changes I'd like to see:

- Removal of non-core features from primary lib (TraceKit.wrap, source code fetching, setTimeout/setInterval patching)
- useragent is a constant, and should not constantly be added to objects
- mode = failed doesnt make a lot of sense; its conflating concerns between status result and method of operation

**Comment by niemyjski** [comment]
I've been wanting to bring these changes in. Could you please do two separate pull requests for the first two with a very brief  explanation of last args and report and what issues you saw / fixed. This would be a huge help as I'm in the middle of writing unit tests.

I want to ditch user agent completely. What is mode even used for? I thought we could ditch that too as I wasn't sure what value it added.

For removal of non core features.. This is coming but we need unit tests first. Then the features we remove will be plugins or a compat shim so we don't break existing people

**Comment by dcramer** [comment]
We have no desire to help maintain TraceKit upstream at this time. To be frank have too much other stuff to do. I personally don't work on raven.js, and when it comes down to it we don't need 50% of the code in the project. I'd rather invest our time into removing TraceKit than pushing more changes upstream, but we're willing to reconsider that if upstream maintainers can push in the same direction as us.

Regarding the changes, the first because the code is broken today without it, and the other because this code should have nothing to do with window.onerror. Historically TraceKit has conflated "i want to solve window.onerror" with "i just want actual exceptions to work correctly".  Unless you change it so that 'TraceKit.report is only for window.onerror' then there's really no reason it should ever be throwing exceptions by default.

**Comment by niemyjski** [comment]
We don't expect you to contribute but it would be helpful (I can diff it as well). Yeah I agree some things need to change and they will.

**Comment by dcramer** [comment]
https://github.com/getsentry/raven-js/pull/315 as it points out whatever the original change was is currently incorrect

**Comment by niemyjski** [comment]
I just got rid of user agent and url. More work to do but it's a start.

**Comment by niemyjski** [comment]
I'm one step closer to bringing in the raven changes. I just finished the unit tests a few weeks ago and need to get this working this weekend.

**Comment by niemyjski** [comment]
@dcramer I'm going to close this. I've merged in the changes we both felt were needed. We need to add some kind of flag to report but I kinda want to overhaul it very soon with plugins (creating a branch now). We need this flag as it directly effects #32
